### ISSUE TITLE
TypeError when transform "face_region_mask" from numpy to torch

### ISSUE THREAD

**Issue by Yozey** [zqbai-jeremy/DFNRMVS#1]
Hi, thank you very much for your work and the code, it is very interesting.

I tried to run your demo. However, there were sth wrong while transforming "face_region_mask" from numpy to torch.

> Traceback (most recent call last):
>   File "demo.py", line 143, in <module>
>     model = init_model(checkpoint_path)
>   File "demo.py", line 47, in init_model
>     model = FNRMVSNet(opt_step_size=1e-2)
>   File "/home/yyan/3d_reco/DFNRMVS/networks/sub_nets.py", line 1083, in __init__
>     self.opt_layer = NRMVSOptimization(opt_step_size=opt_step_size, MM_base_dir=MM_base_dir)
>   File "/home/yyan/3d_reco/DFNRMVS/networks/sub_nets.py", line 558, in __init__
>     self.bfm_torch = bfm_utils.MorphabelModel_torch(self.bfm)
>   File "/home/yyan/3d_reco/DFNRMVS/data/BFM/utils.py", line 589, in __init__
>     self.face_region_mask = torch.from_numpy(bfm.face_region_mask).unsqueeze(0)                 # (1, nver, 1)
> TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.

There is probably an easy hotfix. However, I am new to your code so I am not quite sure what is an appropriate type for your `self.face_region_mask`. 
Could u please have a look? Thank you very much.

**Comment by zqbai-jeremy** [comment]
I didn't get this error during testing. It's probably because I use Pytorch 1.3.1. `self.face_region_mask` is basically 0 or 1. It has been explicitly converted to other types when being accessed, so any float or int should be fine.

**Comment by Yozey** [comment]
Thanks for your helpful response. Problem solved after updating my torch to 1.5 version.

Probably some packages in `requirements_conda.txt` prevent the installation of the lastest torch version (by default it was 1.0 version), but I am not quite sure about it. Hope that helps others who may encounter the same problem.

Thanks for your excellent work and for sharing the code.
