### ISSUE TITLE
想看到Landmark数据和Multi-Level重建

### ISSUE THREAD

**Issue by darktrident** [zqbai-jeremy/DFNRMVS#10]
您好，我在用自己的照片想复现您这篇面部重建，请问我要修改什么语句可以看到检测面部Landmark的数据，和分别看到三个不同精度Level的脸部模型呢？谢谢！

**Comment by zqbai-jeremy** [comment]
你好。landmark检测部分在demo.py里的preprocess(.)函数，用的是face_alignment (https://github.com/1adrianb/face-alignment)。不同精度的vertices positions存在demo.py里的predict(.)函数里的opt_verts[level=1,2,3][iteration=1,2,3]变量，level 0 是mean shape，1到3精度逐渐变高。

**Comment by darktrident** [comment]
好的。谢谢！
